name: Push Image (manual)

on:
  workflow_dispatch:
    branches:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - id: commit
        uses: pr-mpt/actions-commit-hash@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout to waku-frontend
        uses: actions/checkout@v3
        with: 
          repository: waku-org/waku-frontend

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: Setup npm
        uses: bahmutov/npm-install@v1

      - name: Artefact build
        run: npm run build

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          # temporal, migrate to waku-org
          tags: alrevuelta/waku-frontend:${{ steps.commit.outputs.short }} , alrevuelta/waku-frontend:latest
          build-args: BUILD_VERSION=${{ steps.commit.outputs.hash }}
